name = "llama-wasm-test"
version = "1.0.0"

[deployment]
nodes = 1

[build]
dir = "build"
entry = "llama-wasm-test_debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "llama-wasm-test.wasm"
command = "npm run build:release"
